### PR TITLE
Added few guides on how to query MongoDB efficiently 

### PR DESCRIPTION
**Pull request by patelswapnil**
This PR adds guide on how to query MongoDB in an efficient way.

### To verify
 - @smebberson to verify all performance optimisation tips in the guide.

### CODE REVIEW

**Comment by patelswapnil** [comment]
@smebberson, this PR has been created for you to review the performance optimisation guide for MongoDB.

**Comment by allanchau** [comment]
@idearium/developers Same here, do you think this is still needed?
It is good, but I don't think it is specific to Idearium.

**Comment by smebberson** [comment]
I agree that it is not very specific. I like the content though. Do you think it's worth updating to be more specific showing the Idearium way of doing those things?

**Comment by allanchau** [comment]
@smebberson Yeah, I actually plan on creating a PR for Idearium-lib to add to our `query.js` file and turn it into a Mongoose plugin.

You would use it like
```javascript
const Model = linz.api.model.get('modelName');

Model.findOneDocument({
    filter: {},
    lean: true,
   ...
})

Model.findDocuments({
    filter: {},
    lean: true,
   ...
})
```

Perhaps leave this open and I will update it when I get around to doing that?

**Comment by smebberson** [comment]
Awesome, that sounds good :)

**Comment by smebberson** [comment]
We no longer require this.

**Pull request closed without merging**
